---
substitutions:
  system_name: attic-office-plug-desk
  host_name: attic-office-plug-desk.bjw-s.internal
  friendly_name: Attic Office - Desk Plug
  device_description: CloudFree P1EU
  current_res: "0.00243"
  voltage_div: "963"

packages:
  device: !include devices/cloudfree_p1eu.yaml
