---
substitutions:
  system_name: attic_office_desk_plug
  host_name: attic-office-desk-plug.bjw-s.casa
  friendly_name: Attic Office - Desk Plug
  device_description: CloudFree P1EU plug that controls attic office desk power
  current_res: "0.00243"
  voltage_div: "963"

packages:
  device: !include devices/cloudfree_p1eu.yaml
