---
substitutions:
  system_name: attic-office-plug-homelab
  friendly_name: Attic Office - Homelab Plug
  device_description: Athom ESP32-C3 EU Plug

packages:
  device: !include
    file: athom-c3-eu/base.yaml
