---
substitutions:
  system_name: attic-office-ac-controller
  host_name: attic-office-ac-controller.bjw-s.internal
  friendly_name: Attic Office - AC Controller
  device_description: Generic ESP32 that controls the attic office AC
  temperature_sensor_entity_id: sensor.attic_office_temperature


packages:
  device: !include devices/esphome_lg_controller.yaml
