---
substitutions:
  system_name: attic-office-plug-3dprinter
  host_name: attic-office-plug-3dprinter.bjw-s.internal
  friendly_name: Attic Office - 3DPrinter Plug
  device_description: CloudFree P1EU plug
  current_res: "0.00245"
  voltage_div: "963"

packages:
  device: !include devices/cloudfree_p1eu.yaml
