---
substitutions:
  system_name: attic-office-presence-esp
  friendly_name: Attic Office - Presence ESP
  device_description: Apollo MSR-2 mmwave multisensor

packages:
  device: !include
    file: apollo-msr2/base.yaml
  bluetooth-proxy: !include
    file: esphome-common/bluetooth-proxy.yaml
