---
substitutions:
  system_name: bedroom-eva-presence-esp
  host_name: bedroom-eva-presence-esp.bjw-s.internal
  friendly_name: Bedroom Eva - Presence ESP
  device_description: M5Stack Atom Presence Detector

packages:
  device: !include devices/m5stack-atom-presence-detector.yaml
