---
substitutions:
  system_name: bedroom-bed-occupancy-left
  host_name: bedroom-bed-occupancy-left.bjw-s.internal
  friendly_name: Bedroom - Bed Occupancy Left
  device_description: Apollo MSR-2 Presence detector

packages:
  device: !include devices/apollo_msr2_base.yaml
