---
# zigbee_chipset:          EFR32MG21
# zigbee_firmware_url:     https://github.com/darkxst/silabs-firmware-builder/releases/20241106/
# zigbee_firmware_version: ncp-8.0.2.0-sw_flow

substitutions:
  system_name: downstairs-hallway-slzb06
  friendly_name: Downstairs Hallway - SLZB06
  device_description: SMLight SLZB06M

packages:
  device: !include
    file: smlight-slzb06/base.yaml
  auto-restart: !include
    file: esphome-common/auto-restart.yaml
