---
substitutions:
  system_name: hallway_zigbee_adapter
  host_name: hallway-zigbee-adapter.bjw-s.tech
  friendly_name: Hallway - Zigbee Adapter
  device_description: TubesZB PoE Zigbee Coordinator

packages:
  device: !include devices/tubeszb-cc2652-poe.yaml

