---
substitutions:
  system_name: livingroom-presence-esp
  friendly_name: Living Room - Presence ESP
  device_description: M5Stack Atom Presence Detector

packages:
  device: !include
    file: m5stack-atom/base.yaml
  bluetooth-proxy: !include
    file: esphome-common/bluetooth-proxy.yaml
