---
substitutions:
  system_name: spare_p1eu_2
  # host_name: 10.1.3.227
  friendly_name: Spare P1EU 2
  device_description: CloudFree P1EU plug
  current_res: "0.00245"
  voltage_div: "963"

packages:
  device: !include devices/cloudfree_p1eu.yaml
