---
# Espressif ESP32 Dev Module
#
# https://docs.platformio.org/en/latest/boards/espressif32/esp32dev.html
#
esphome:
  <<: !include .esphome.yaml

esp32:
  board: esp32dev
  framework:
    type: arduino
