---
# Espressif ESP32-C3-DevKitM-1
#
# https://docs.platformio.org/en/stable/boards/espressif32/esp32-c3-devkitm-1.html
#

esphome:
  <<: !include .esphome.yaml

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf  # This is important: the default "arduino" framework does not perform well.
    sdkconfig_options:
      # BLE 4.2 is supported by ALL ESP32 boards that have bluetooth, the original and derivatives.
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Also enable this on any derivative boards (S2, C3 etc) but not the original ESP32.
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      # Extend the watchdog timeout, so the device reboots if the device appears locked up for over 10 seconds.
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
