---
substitutions:
  system_name: garage-plug-freezer
  friendly_name: Garage - Freezer Plug
  device_description: Athom PG01 ESP32-C3 EU Plug

packages:
  device: !include
    file: athom-pg01-c3-eu/base.yaml
