---
# Bluetooth Proxy component package
# https://esphome.io/components/bluetooth_proxy.html
#
substitutions:
  ble_scan_interval: 320ms
  ble_scan_window:    30ms

bluetooth_proxy:
  active: true  # allows outbound connections from HA to devices.

esp32_ble_tracker:
  scan_parameters:
    active: true  # send scan-request packets to gather more info, like device name for some devices.
    interval: ${ble_scan_interval}
    window:   ${ble_scan_window}
