# Device: LG Airco ESP controller
# Config is based on https://github.com/JanM321/esphome-lg-controller/blob/main/esphome/base.yaml
#

substitutions:
  # The input temperature sensor in HA.
  temperature_sensor_entity_id: ""
  # If multiple controllers are connected to a single indoor unit, only one of them should be
  # configured as "master controller". Slave mode is a new and experimental feature for this
  # ESPHome controller and might not work well.
  # If you're connecting a single controller, this should be set to "false".
  is_slave_controller: "false"

packages:
  <<: !include_dir_named ../components/common
  wifi: !include ../components/hardware/wifi.yaml
  board: !include ../boards/nodemcu-32s.yaml
  bluetooth_proxy: !include ../components/hardware/bluetooth_proxy.yaml

uart:
  - id: ac_serial
    tx_pin: GPIO25
    rx_pin:
      number: GPIO26 # Keep in sync with rx_pin below.
      allow_other_uses: true
    baud_rate: 104

sensor:
  - id: temp_sensor
    platform: homeassistant
    internal: true
    entity_id: ${temperature_sensor_entity_id}

external_components:
  - source:
      type: git
      url: https://github.com/JanM321/esphome-lg-controller
      ref: 9964e0ad8316ac971dcfcd284e475792635b8043
    components:
      - lg_controller

climate:
  - platform: lg_controller
    name: Controller
    id: ac_controller
    uart_id: ac_serial
    rx_pin:
      number: GPIO26 # Keep in sync with rx_pin above.
      allow_other_uses: true
    fahrenheit: false
    is_slave_controller: ${is_slave_controller}
    temperature_sensor: temp_sensor
    vane1:
      name: Airflow 1 Up/Down
      id: vane_position_1
      icon: mdi:arrow-up-down
    vane2:
      name: Airflow 2 Up/Down
      id: vane_position_2
      icon: mdi:arrow-up-down
    vane3:
      name: Airflow 3 Up/Down
      id: vane_position_3
      icon: mdi:arrow-up-down
    vane4:
      name: Airflow 4 Up/Down
      id: vane_position_4
      icon: mdi:arrow-up-down
    overheating:
      name: Over Heating
      id: overheating
      icon: mdi:heating-coil
    fan_speed_slow:
      name: Fan Speed Slow
      id: fan_speed_slow
      icon: mdi:fan-chevron-down
      mode: box
    fan_speed_low:
      name: Fan Speed Low
      id: fan_speed_low
      icon: mdi:fan-speed-1
      mode: box
    fan_speed_medium:
      name: Fan Speed Medium
      id: fan_speed_medium
      icon: mdi:fan-speed-2
      mode: box
    fan_speed_high:
      name: Fan Speed High
      id: fan_speed_high
      icon: mdi:fan-speed-3
      mode: box
    sleep_timer:
      name: Sleep Timer (minutes)
      id: sleep_timer
      icon: mdi:timer-outline
      mode: box
    error_code:
      name: Error Code
      id: error_code
      icon: mdi:alert-circle-outline
    pipe_temp_in:
      name: Pipe Temperature In
      id: pipe_temperature_in
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    pipe_temp_mid:
      name: Pipe Temperature Mid
      id: pipe_temperature_mid
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    pipe_temp_out:
      name: Pipe Temperature Out
      id: pipe_temperature_out
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    defrost:
      name: Defrost
      id: defrost
      icon: mdi:snowflake-melt
    preheat:
      name: Preheat
      id: preheat
      icon: mdi:heat-wave
    outdoor:
      name: Outdoor Unit
      id: outdoor
      icon: mdi:fan
    auto_dry_active:
      name: Auto Dry Active
      id: auto_dry_active
      icon: mdi:fan-clock
    purifier:
      name: Air Purifier
      id: air_purifier
      icon: mdi:pine-tree
    internal_thermistor:
      name: Internal Thermistor
      id: internal_thermistor
      icon: mdi:thermometer
    auto_dry:
      name: Auto Dry
      id: auto_dry
      icon: mdi:fan-clock
