---
# Device: M5Stack Atom Presense detector
#

packages:
  <<: !include_dir_named ../components/common
  wifi: !include ../components/hardware/wifi.yaml
  board: !include ../boards/m5stack-atom.yaml
  bluetooth_proxy: !include ../components/hardware/bluetooth_proxy.yaml

substitutions:
  ble_scan_interval: 211ms
  ble_scan_window: 120ms
