---
# Device: SMLight SLZB06x Zigbee adapter
# Config is based on https://github.com/smlight-dev/slzb-06-fw-esphome

packages:
  <<: !include_dir_named ../components/common
  board: !include ../boards/esp32dev.yaml

esphome:
  on_boot:
    priority: 600
    then:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

esp32:
  flash_size: 16MB

external_components:
  - source: github://tube0013/esphome-stream-server-v2

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  use_address: "${host_name}"

uart:
  id: uart_bus
  rx_pin: GPIO5
  tx_pin: GPIO17
  baud_rate: 115200

stream_server:
  uart_id: uart_bus
  id: streamServer
  port: 6638

binary_sensor:
  # - platform: gpio
  #   name: "Physical button"
  #   icon: mdi:toggle-switch
  #   id: gpio35btn1
  #   pin:
  #     number: GPIO35
  #     mode:
  #       input: true
  #     inverted: yes
  #   on_press:
  #     then:

  - platform: stream_server
    stream_server: streamServer
    name: "Serial Connected"

text_sensor:
  - platform: template
    name: Zigbee chipset
    icon: mdi:memory
    lambda: |-
      return to_string("${zigbee_chipset}");
  - platform: template
    name: Zigbee firmware version
    icon: mdi:calendar-import
    lambda: |-
      return to_string("${zigbee_firmware_version}");

button:
  - platform: template
    name: "Zigbee Restart"
    icon: mdi:restart
    id: restart_zigbee
    on_press:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

  - platform: template
    name: "Full (ESP + Zigbee) Restart"
    icon: mdi:restart-alert
    id: restart_full
    on_press:
      - button.press: restart_zigbee
      - delay: 15ms
      - button.press: restart_esp

switch:
  ## Zigbee Restart
  - platform: gpio
    pin: 33
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF

  ## Zigbee to flash mode switch
  - platform: gpio
    pin: 32
    name: "Zigbee flash Mode internal"
    icon: mdi:toggle-switch
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    internal: true
  - platform: template
    name: "Zigbee flash Mode"
    icon: mdi:cellphone-arrow-down
    turn_on_action:
      - script.execute: fw_update_mode
    turn_off_action:
      - button.press: restart_zigbee

script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
      - logger.log: "Wait 1 seconds for Zigbee chip to be ready"
      - delay: 1s
      - switch.turn_off: zBSL
      - logger.log: "Update Zigbee with your firmware now!"
