---
# Device: TubesZB Zigbee Coordinator
# CC2652P2 Radio Module + Olimex ESP32-PoE Module
#

packages:
  <<: !include_dir_named ../components/common
  board: !include ../boards/esp_wrover_kit.yaml

substitutions:
  host_name: "${host_name}"

external_components:
  - source: github://tube0013/esphome-stream-server-v2
  - source: github://syssi/esphome-zeroconf@main

ethernet:
  use_address: "${host_name}"
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
      - logger.log: "Delaying ~10 seconds for cc2652p2 to settle"
      - delay: 11s
      - switch.turn_off: zBSL
      - logger.log: "Please try update with cc-bsl tool now"
      - logger.log: "cc-bsl usage: cc-bsl.py -p socket://ip-of-gw:6638 -evw firmware.hex"

switch:
  - platform: gpio
    pin: 13
    id: zRST_gpio
    inverted: true
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "zRST"
    id: zRST
    turn_on_action:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

  - platform: gpio
    pin: 4
    name: "zBSL"
    id: zBSL
    inverted: true
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "Prep the cc2652p2 for firmware update"
    turn_on_action:
      - script.execute: fw_update_mode
    turn_off_action:
      - switch.toggle: zRST

uart:
  id: uart_bus
  rx_pin: GPIO5
  tx_pin: GPIO16
  baud_rate: 115200

stream_server:
  uart_id: uart_bus
  id: ss
  port: 6638 # optional, default is 6638

binary_sensor:
  - platform: stream_server
    stream_server: ss
    name: "${friendly_name} Serial Connected"

zeroconf:
  - service: tubeszb
    protocol: tcp
    port: 6638
    txt:
      version: 1.0
      name: TubesZB
      radio_type: znp
      baud_rate: 115200
      data_flow_control: software
