---
substitutions:
  system_name: hallway_doorbell_chime
  host_name: hallway-doorbell-chime-esp
  friendly_name: Hallway - Doorbell Chime
  device_description: Custom ESP8266 board to send KaKu doorbell trigger

packages:
  device: !include devices/custom_esp8266.yaml

esphome:
  includes:
    - components/external/NewRemoteTransmitter

mqtt:
  on_message:
    - topic: amcrest2mqtt/Z17876DEBF0B6/doorbell
      payload: "on"
      then:
        - script.execute: chime_if_not_muted

remote_transmitter:
  pin:
    number: GPIO3
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%

globals:
  - id: var_chime_muted
    type: bool
    restore_value: true
    initial_value: "false"

script:
  - id: chime_if_not_muted
    then:
      - if:
          condition:
            switch.is_off: doorbell_chime_muted
          then:
            - switch.turn_on: trigger_chime

switch:
  - platform: custom
    # Replace the following values: pin, address, period, unit, publish_state
    lambda: |-
      auto customSwitch = new MyNewRemoteTransmitter(3, 45878526, 250, 15, false);
      App.register_component(customSwitch);
      return {customSwitch};

    switches:
      id: trigger_chime
      internal: true

  - platform: template
    name: "${friendly_name} Muted"
    id: doorbell_chime_muted
    restore_state: false
    turn_on_action:
      - globals.set:
          id: var_chime_muted
          value: "true"
    turn_off_action:
      - globals.set:
          id: var_chime_muted
          value: "false"
    lambda: |-
      return id(var_chime_muted);

binary_sensor:
  - platform: gpio
    id: doorbell_button_pressed
    name: "${friendly_name} Button"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
