---
substitutions:
  system_name: bedroom_bed_occupancy
  host_name: bedroom-bed-occupancy-esp.bjw-s.internal
  friendly_name: Bedroom - Bed Occupancy
  device_description: Generic ESP32 that detects bed occupancy

packages:
  device: !include devices/custom_esp32.yaml

esp32_touch:
  measurement_duration: 8ms

binary_sensor:
  - platform: esp32_touch
    name: Bedroom - Bed Occupancy Right
    device_class: occupancy
    pin: GPIO13
    threshold: 3
    id: esptouch_bed_occupancy_right
    filters:
      - delayed_on: 500ms
      - delayed_off: 10s

  - platform: esp32_touch
    name: Bedroom - Bed Occupancy Left
    device_class: occupancy
    pin: GPIO12
    threshold: 3
    id: esptouch_bed_occupancy_left
    filters:
      - delayed_on: 500ms
      - delayed_off: 10s

sensor:
  - platform: template
    name: "Bedroom - Bed Occupancy Right Raw Reading"
    id: "bedroom_bed_occupancy_right_raw_reading"
    update_interval: 10s
    accuracy_decimals: 0
    lambda: |-
      return ((uint32_t) id(esptouch_bed_occupancy_right)->get_value());

  - platform: template
    name: "Bedroom - Bed Occupancy Left Raw Reading"
    id: "bedroom_bed_occupancy_left_raw_reading"
    update_interval: 10s
    accuracy_decimals: 0
    lambda: |-
      return ((uint32_t) id(esptouch_bed_occupancy_left)->get_value());
