---
substitutions:
  system_name: spare_p1eu_1
  host_name: spare-p1eu-1.bjw-s.internal
  friendly_name: Spare P1EU 1
  device_description: CloudFree P1EU plug
  current_res: "0.00245"
  voltage_div: "963"

packages:
  device: !include devices/cloudfree_p1eu.yaml
