---
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

packages:
  esphome-base: !include
    file: ../esphome-common/base.yaml
  wifi: !include
    file: ../esphome-common/wifi.yaml
  entities: !include
    file: entities.yaml
